---
# Debian/Ubuntu GNOME packages

gnome_packages:
  - gnome-core
  - gnome-shell
  - gnome-session

gnome_tweaks_package: gnome-tweaks

dconf_package: dconf-cli

gnome_extension_packages:
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-gsconnect

nm_openvpn_package: network-manager-openvpn-gnome
